import { makeStyles } from "@fluentui/react-components";

export const useSplashStyles = makeStyles({
    screen: {
        position: "fixed",
        top: 0,
        left: 0,
        width: "100%",
        height: "100%",
        background: "linear-gradient(135deg, #1d3557 0%, #2a4365 100%)",
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
        zIndex: 2000,
        // 🌟 Transición de salida suave controlada por React
        transition: "opacity 0.5s ease, visibility 0.5s ease",
    },
    hidden: {
        opacity: 0,
        visibility: "hidden",
    },
    container: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        animation: "fadeInUp 0.8s ease-out",
    },
    logoContainer: {
        position: "relative",
        marginBottom: "2.5rem",
    },
    logoOuter: {
        width: "120px",
        height: "120px",
        borderRadius: "50%",
        background: "rgba(255, 255, 255, 0.1)",
        backdropFilter: "blur(10px)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        position: "relative",
        overflow: "hidden",
        border: "2px solid rgba(255, 255, 255, 0.2)",
        "&::before": {
            content: '""',
            position: "absolute",
            top: "-2px",
            left: "-2px",
            right: "-2px",
            bottom: "-2px",
            background: "linear-gradient(45deg, #e63946, #1d3557, #457b9d)",
            borderRadius: "50%",
            zIndex: -1,
            animation: "rotate 3s linear infinite",
        },
    },
    logoInner: {
        width: "100px",
        height: "100px",
        borderRadius: "50%",
        background: "linear-gradient(135deg, #1d3557 0%, #2a4365 100%)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        color: "white",
        fontSize: "2.5rem",
        fontWeight: 700,
        letterSpacing: "1px",
    },
    textContainer: {
        textAlign: "center",
        color: "white",
    },
    title: {
        fontSize: "2rem",
        fontWeight: 600,
        marginBottom: "0.5rem",
        background: "linear-gradient(to right, white, #a8dadc)",
        WebkitBackgroundClip: "text",
        WebkitTextFillColor: "transparent",
    },
    subtitle: {
        fontSize: "1rem",
        opacity: 0.9,
        marginBottom: "2rem",
        fontWeight: 300,
    },
    progress: {
        width: "300px",
        height: "4px",
        background: "rgba(255, 255, 255, 0.2)",
        borderRadius: "2px",
        overflow: "hidden",
        position: "relative",
    },
    progressBar: {
        position: "absolute",
        top: 0,
        left: 0,
        height: "100%",
        background: "linear-gradient(to right, #e63946, #ff6b6b)",
        borderRadius: "2px",
        transition: "width 0.3s ease",
    },
});